Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/giulio/DRUBER/src/experiments/simulate.py", line 34, in <module>
    solution = S.run(args.algorithm, args.method)
  File "/home/giulio/DRUBER/src/simulation/Simulator.py", line 138, in run
    solution = OPT.solveProblem()
  File "/home/giulio/DRUBER/src/routing/MILPPlanner.py", line 436, in solveProblem
    solution = self.extractSolution()
  File "/home/giulio/DRUBER/src/routing/MILPPlanner.py", line 482, in extractSolution
    for i in range(len(DeliveryPaths[d])):
KeyError: 2
